version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./web:/app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./server:/app
    command:
      - air
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    depends_on:
      - db
      - migrations

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build:
      context: ./server
      dockerfile: Dockerfile
    command:
      [
        "sh",
        "-c",
        "migrate -path db/migrations -database 'postgres://postgres:postgres@db:5432/postgres?sslmode=disable' up",
      ]
    depends_on:
      - db
    volumes:
      - ./server:/app

volumes:
  postgres_data:
