version: "3"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./web:/app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./server:/app
    command:
      - air
