version: "3"
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./server:/app/server

  server:
    build: ./server
    ports:
      - "50051:50051"
